### ISSUE TITLE
Google Docs = Low tech ? 

### ISSUE THREAD

**Issue by ImaCrea** [swallez/gdocs2hugo#1]
hmm je m'interroge sur le côté "low tech" de Google Docs 🤔

**Comment by swallez** [comment]
C'est low tech du point de vue du rédacteur, qui écrit le contenu dans un bête traitement de texte et crée la table des matières du site dans un spreadsheet (avec des liens vers les docs + quelques métadonnées). Pas besoin de connaître WordPress ou un langage type HTML ou Markdown.
